### ISSUE TITLE
görev

### ISSUE THREAD

**Issue by uzeyir-yariz** [webmuhammet/ilkprojem#1]
## öncellikler sırayla

<details>
<summary>Header & Main Update</summary>

- [x] _navbar_ `align-items: center;` olmalı 
- [ ] _main_ bölümü içinde ki _article_ slogan ve sloganı açıklayan söz `margin-top: ...;` `margin-left: ...;` ile ayrılmalı
- [x] _main_ tam ortaya gelmeli 
- [x] arka plana bir resim yerleştir [yardım için tıkla](https://www.w3schools.com/html/html_images_background.asp)
</details>

<details>
<summary>Footer Update</summary>

### footer için istenenler _üst kısmı görmezden gelebilirsiniz_ <span>
![image](https://user-images.githubusercontent.com/99393019/205075427-0ea7276a-faaa-4f9f-a505-78afeca4cc9b.png)

her biri için article/div kullanılabilir _size kalmış_

<details>
<summary>Footer Up ve Down Zor Kısım</summary>

- [x] footer içine iki div/article ekle yukardakine `class="up"` alttakine ise `class="down"` ver 
- [x] up class'ına article ve img ekle . `.up{ flex-director: row; }`  
- [ ] up class'ın da ki article içine h6, h4, input  [yardım için tıkla](https://www.netsparker.com.tr/blog/web-guvenligi/form-ve-input-elemanlarinda-autocomplete-kullanimi/)
- [ ] article `article{ flex-director: collum; }` 
- [ ] down class'ın içine 4 div ekle divler `.down{ flex-director: row; }` divlerin içindekiler collumn olucak
- [ ] 4. div istisna bir durum var burada 4. divin içine iki div daha eklemen önerilir  
- [ ] 4. div collum olucak 
- [ ] 4. div'in ilk çocuğu collum olucak 
- [ ] 4. div'in çocuğu row olucak _bu sayede sıralı olucak_
</details>

<details>
<summary>Footer Down Kolay Kısım</summary>

- [ ] down class'ın içine 4 div ekle divler `.down{ flex-director: row; }` divlerin içindekiler collumn olucak
- [ ] 4. div istisna bir durum var burada 4. divin içine iki div daha eklemen önerilir  
- [ ] 4. div collum olucak 
- [ ] 4. div'in ilk çocuğu collum olucak 
- [ ] 4. diolucak _bu sayede sıralı olucak_
</details>

**Comment by webmuhammet** [comment]
1 Ara 2022 Per 18:14 tarihinde uzeyir-yariz ***@***.***> şunu
yazdı:
